---
title: "Reduce Sugar Consumption"
author: "Karin Altvater, Santosh Bhandari, Patrick Frey, Sanghyo Moon"
date: "2023-06-16"
output: ioslides_presentation

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Countries with Sugar Sweetened Beverage Tax

```{r ,include=F, echo=F}
library(tmap)
data(World)
library(readxl)
library(raster)
library(sp)

SSB_Tax_Database_Feb23 <- read_excel("Sanghyo/SSB-Tax-Database-Feb23.xlsx")
SSB_World <- merge(World, SSB_Tax_Database_Feb23, by.x="iso_a3", by.y="wb_code")

A <- tm_shape(World)+
  tm_polygons()+
  tm_shape(SSB_World)+
  tm_polygons("SSB-Tax")+
  tm_layout(main.title = "Countries with SSB -Tax",
            main.title.position = "center",
            main.title.color = "#003333")+
  tm_text(text = "iso_a3", size = 0.2)

```

```{r }
A
```

## Input modell

```{r echo=F}
library(decisionSupport)
library(DiagrammeR)
grViz("digraph {
  
graph[layout = dot, rankdir = LR]
node[style = filled, margin = 0.1, fillcolor = 'azure']


I   [label = 'Input for Decision']
pos [label = 'Positiv Support', fillcolor = 'green']
neg [label = 'Negativ Support', fillcolor = 'red']

sh  [label = 'Stakeholder', shape = rectangle]
res [label = 'Results of Countries', shape = rectangle]

gov [label = 'Goverment', shape = rectangle]
ind [label = 'Individuals', shape = rectangle]
sm [label = 'Supermarkets', shape = rectangle]
man [label = 'Manufactories', shape = rectangle]

rs  [label = 'Research', shape = rectangle]

gov, ind, sm, man -> sh -> pos, neg
rs -> res
res -> pos, neg 
pos, neg -> I

}")
```

## Decision Modell

```{r echo=F}

library(DiagrammeR)

DiagrammeR::grViz("digraph {
  
graph[layout = dot, rankdir = RR]
node[style=filled]

3 [label = 'SUGAR TAX', shape = triangle]
4 [label = 'Outcome']
5 [label = 'Good', shape = hexagon, fillcolor= 'green']
6 [label = 'Bad', shape = hexagon, fillcolor = 'firebrick']
7 [label = 'Decision', shape = cylinder, fontsize= 24, style='bold']
8 [label = 'NO SUGAR TAX', shape = invtriangle]
9 [label = 'Outcome']
10 [label = 'Good', shape = hexagon, fillcolor = 'green']
11 [label = 'Bad', shape = hexagon, fillcolor = 'firebrick']

          7-> 3->4 -> 5, 6
          7-> 8-> 9 -> 10, 11
          5->3 [color= 'green']
          6->8 [style= 'dashed', color='firebrick']
          10->8 [color = 'green']
          11->3 [style= 'dashed', color='firebrick']
}")
```
